# ===============================
# Application Info
# ===============================
spring.application.name=notification-service
server.port=8081

# ===============================
# Service Endpoints
# ===============================

authService.notification.url=/fitStudio/auth/notification/
authService.admin-notification.url=/fitStudio/auth/admin
messageOrReport.notification.url=/fitStudio/notification/message
adminService.url=/fitStudio/admin/notification/
productService.url=
trainerService.url=
memberService.url=/fitStudio/member/notification
plan-paymentService.url=/fitStudio/plan-payment/notification

# ===============================
# Email Configuration (SendGrid)
# ===============================
app.mail.sender=${sender_mail}
app.mail.secret_key=${SENDGRID_API_KEY}
# ===============================
# Email Configuration (mail jet)
# ===============================
mailjet.mail.sender=${sender_mail_jet}
mailjet.name.sender=${sender_name}
mailjet.api.key=${MAILJET_API_KEY}
mailjet.secret.key=${MAILJET_SECRET_KEY}
# ===============================
# SMS Configuration (Fast2SMS)
# ===============================
fast2sms.api.key=${FAST2SMS_API_KEY}

# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=DEBUG

# ===============================
#   Frontend endpoints
# ===============================
frontend.dashboard.url=${frontend.dashboard}
frontend.plans.url=${frontend.plans}

