spring.application.name=planService
# =======================================
# MICROSERVICE CONFIGURATION
# =======================================
server.port=8085
app.plan-service.baseUrl=http://localhost:8085/fitStudio/plan-service
# ===============================
# Database Configuration (MySQL on AWS RDS)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/planservice?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Redis Configuration
# ===============================
spring.data.redis.host=${host_name_redis}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
logging.level.org.springframework.cache=TRACE


# ========================================
# ENDPOINT CONFIGURATION
# ========================================
plan-service.Base_Url.planManagement=/fitStudio/plan-service/plan
plan-service.Base_Url.cuponManagement=/fitStudio/plan-service/cupon
payment-service.Base_Url.Pay=/fitStudio/payment-service
payment-service.Base_Url.Matrices=/fitStudio/payment-service/matrices
app.notification-service.Base_Url=http://localhost:8081/fitStudio/plan-payment/notification
app.member-service.Plan_Url=http://localhost:8083/fitStudio/member-service/plan
# ===============================
# Aws S3
# ===============================
aws.access.key=${aws_access_key}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=${aws_region}
aws.s3.bucket=${aws_bucket_name}
# ===============================
# Razorpay
# ===============================
razorpay.api.key=${RAZORPAY_KEY_ID}
razorpay.api.secret=${RAZORPAY_KEY_SECRET}